employerprofile/urls.py
from django.urls import path
from .views import *

app_name = 'employerprofile'

urlpatterns = [
    path('profile/',profile,name='profile'),
    path('edit-profile/',proedit,name='proedit'),
    path('create-job/',createjob,name='create_job'),
    path('edit-job/<str:pk>/',editjob,name='create_job'),
    path('listjob/',listjob,name='listjob'),
]

jobapp/urls.py
from django.urls import path
from .views import *

app_name = 'jobapp'

urlpatterns = [
    path('',HomeView.as_view(),name='index'),
    path('register/',register,name='register_employer'),
    path('signin/',signin,name='login'),
    path('logout/',logoutuser,name='logout'),
    path('list/',JobList.as_view(),name='job_list'),
    path('details/<pk>/',JobDetails.as_view(),name='job_details'),
    path('apply/<str:id>/',apply_page,name='apply'),
]

jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls')),
    path('',include('employerprofile.urls'))
]





if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employerprofile/models.py
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import User

# Create your models here.   

class Employer(models.Model):
    gender=(
        ('Male','male'),
        ('Female','female'),
        ('Other','other'),
    )
    username =models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name=models.CharField(max_length=200,blank=True, null=True)
    dob=models.DateField(blank=True, null=True)
    gender= models.CharField(max_length=200, blank=True, null=True, choices=gender)
    company_contact= models.CharField(max_length=200, blank=True, null=True)
    email= models.EmailField(unique=True)
    company_name =models.CharField(max_length=200,blank=True, null=True)
    company_address=models.TextField(blank=True, null=True)
    website=models.URLField(blank=True, null=True)

    def __str__(self):
        return self.username.username

jobapp/models.py
from django.utils import timezone

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from employerprofile.models import Employer

# Create your models here.


class Category(models.Model):
    DELAY = (("1", "0.1"), ("2", "0.3"), ("3", "0.5"), ("4", "0.7"))
    name =models.CharField(max_length=200,null=True)
    delay = models.CharField(max_length=2, choices=DELAY,blank=True,null=True)
    def __str__(self):
        return self.name
    
    # def get_absolute_url(self):
    #     return reverse ("jobapp:job_list", kwargs ={'name': self.name})


class Job(models.Model):
    JOB_TYPE = (("1", "Full time"), ("2", "Part time"), ("3", "Internship"))
    employer =models.ForeignKey(Employer, on_delete=models.CASCADE, null=True, blank=True)
    title =models.CharField(max_length=200)
    type = models.CharField(choices=JOB_TYPE, max_length=10)
    description=models.TextField(blank=True,null=True)
    salaryrange=models.CharField(max_length=50,blank=True,null=True)
    salary=models.IntegerField(default=0, blank=True,null=True)
    Location=models.CharField(max_length=2000, blank=True,null=True)
    category =models.ForeignKey(Category,on_delete=models.CASCADE, null=True, blank=True)
    last_date = models.DateTimeField(null=True, blank=True)
    company_name = models.CharField(max_length=100)
    company_description = models.TextField()
    website = models.CharField(max_length=100, default="")
    created_at = models.DateTimeField(default=timezone.now)
    filled = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} posted by {self.employer.name}"
    
    def get_absolute_url(self):
        return reverse ("jobapp:job_details", kwargs ={'pk': self.pk})
    


class Applicant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    firstname = models.CharField(max_length=80, blank=True, null=True)
    lastname = models.CharField(max_length=80, blank=True, null=True)
    email = models.EmailField(unique=True, blank=True, null=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name="applicants")
    created_at = models.DateTimeField(default=timezone.now)
    comment = models.TextField(blank=True, null=True)
    status = models.SmallIntegerField(default=1)
    resume = models.FileField(upload_to='resumes/')
    cover_letter = models.TextField()

    class Meta:
        ordering = ["id"]
        unique_together = ["user", "job"]

    def __str__(self):
        return f"{self.firstname} applied for {self.job.title} job"

    @property
    def get_status(self):
        if self.status == 1:
            return "Pending"
        elif self.status == 2:
            return "Accepted"
        else:
            return "Rejected"



        

employerprofile/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import *

from jobapp.forms import *
from jobapp.views import G


# Create your views here.

############################### PROFILE ##################################
@login_required(login_url='loggin')
def profile(request):
    profile = G.employer.get(username__username= request.user.username)

    return render (request, 'pages/profile.html', {'profile': profile,})

@login_required(login_url='loggin')
def proedit(request):
    load_profile = G.employer.get(username__username= request.user.username)
    form = ProfileForm(instance=request.user.employer)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.employer)
        if form.is_valid():
            form=form.save()
            return redirect('employerprofile:profile')
        else:
           return redirect('employerprofile:profile')

    context = {
        'load_profile': load_profile,
        'form':form,
    }
    return render(request, 'pages/proedit.html', context)

############################## PROFILE END ##################################

############################## JOB CREATE AND EDIT ##################################
@login_required(login_url='loggin')
def createjob(request):
    form=CreateJobForm(instance= request.user.employer)
    if request.method=='POST':
        form=CreateJobForm(request.POST, instance= request.user.employer)
        if form.is_valid():
            form.save()
            return redirect('jobapp:job_list')
    return render(request,'job/create_job.html',{'form':form})

@login_required(login_url='loggin')
def editjob(request, pk):
    jobdetails = G.job.get(pk=pk)
    form=CreateJobForm(instance= jobdetails)
    if request.method=='POST':
        form=CreateJobForm(request.POST, instance=jobdetails)
        if form.is_valid():
            form.save()
            return redirect('jobapp:job_details', jobdetails.pk)
        
    return render(request,'job/create_job.html',{'form':form})

############################## JOB CREATE AND EDIT END ##################################

@login_required(login_url='loggin')
def listjob(request):
    list = G.job.filter(employer= request.user.employer)

    return render (request, 'job/listjob.html', {'list': list,})

employerprofile/templates/job/create_job.html
{% extends 'main.html' %}

{% block content %}
<div>
    <form method="POST" action="">
        {% csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
</div>

{% endblock %}

employerprofile/templates/job/listjob.html
{% extends "main.html" %}

{% load static %}


<!-- title section -->


{%block navbar%}
{% include 'home/navbar.html' %}     
{% endblock %}

<!--content -->
{% block content %}
<div class="container-flui">
    <div class="row justify-content-start">
        <div class="col-12 col-md-3">
            <nav class="navbar navbar-expand-sm navbar-light bg-transparent nav-edit">
                <a class="navbar-toggler border-0" type="button" data-toggle="collapse" href="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                    <!-- <span class="navbar-toggler-icon"></span> -->
                    <span class="navbar-toggler-icon rounded log" style="font-size: 1rem;"></span>
                    <!-- <span><strong>SideBar</strong></span> -->
                </a>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0" style="display: inline-block;">
                        <a class="nav-link mb-3 link-edit" href="#"><i class="fas fa-files"></i>Dashboard <i class="fas fa-files text-primary"></i></a>
                        <a class="nav-link mb-3 profdit" href="{% url 'employerprofile:proedit' %}">Update</a>
                        <a class="nav-link mb-3 link-edit" href="{% url 'employerprofile:create_job' %}">Post Job</a>
                        <a class="nav-link mb-3 link-edit active" href="#item-1">Job Posted</a>
                        <a class="nav-link profditt mb-3" href="{% url 'employerprofile:profile' %}"> Profile </a>
                        <a class="nav-link mb-3 profdit" href="#">Change Password</a>
                        <a class="nav-link mb-3 link-edit" href="#">Appointment</a>
                        <a class="nav-link mb-3 link-edit" href="#">Prescription</a>
                        <a class="nav-link text-muted link-editt" href="#"><small>Help And Support</small></a>
                        <a class="nav-link text-muted link-edite" href="#">Preferences</a>
                    </ul>
                </div>
            </nav>  
        </div>
        <div class="col-12 col-md-9 profile-col">
            <div data-spy="scroll" data-target="#navbar-example3" data-offset="0">
                <p id="item-1">
                    <!-- Jobs Start -->
                    <div class="container-xxl py-5">
                        <div class="container">
                            <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Job Listing</h1>
                            <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
                                <div class="tab-content">
                                    <div id="tab-1" class="tab-pane fade show p-0 active">
                                        <div class="job-item p-4 mb-4">
                                            {% if list %}
                                                {% for i in list %}
                                                    <div class="row g-4">
                                                        <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                                            <img class="flex-shrink-0 img-fluid border rounded" src="{% static '' %}img/com-logo-1.jpg" alt="" style="width: 80px; height: 80px;">
                                                            <div class="text-start ps-4">
                                                                <h5 class="mb-3">{{ i.title }}</h5>
                                                                <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>{{ i.Location }}</span>
                                                                <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>{{ i.get_type_display }}</span>
                                                                {% if i.salaryrange == Null %}
                                                                    <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>{{ i.salary }}</span>
                                                                {% else %}
                                                                    <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>{{ i.salaryrange }}</span>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                        <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                                            <div class="d-flex mb-3">
                                                                <a class="btn btn-light btn-square me-3" href="#"><i class="far fa-heart text-primary"></i></a>
                                                                <a class="btn btn-primary" href="{% url 'jobapp:apply' i.pk %}">Apply Now</a>
                                                            </div>
                                                            <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: {{ i.last_date }}</small>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                        <a class="btn btn-primary py-3 px-5" href="">Browse More Jobs</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Jobs End -->
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}