employerprofile/urls.py
from django.urls import path
from .views import *

app_name = 'employerprofile'

urlpatterns = [
    path('profile/',profile,name='profile'),
    path('edit-profile/',proedit,name='proedit'),
    path('create-job/',createjob,name='create_job'),
    path('edit-job/<str:pk>/',editjob,name='create_job'),
    path('listjob/',listjob,name='listjob'),
]

jobapp/urls.py
from django.urls import path
from .views import *

app_name = 'jobapp'

urlpatterns = [
    path('',HomeView.as_view(),name='index'),
    path('register/',register,name='register_employer'),
    path('signin/',signin,name='login'),
    path('logout/',logoutuser,name='logout'),
    path('list/',JobList.as_view(),name='job_list'),
    path('details/<pk>/',JobDetails.as_view(),name='job_details'),
    path('apply/<str:id>/',apply_page,name='apply'),
]

jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls')),
    path('',include('employerprofile.urls'))
]





if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobapp/models.py
from django.utils import timezone

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from employerprofile.models import Employer

# Create your models here.


class Category(models.Model):
    DELAY = (("1", "0.1"), ("2", "0.3"), ("3", "0.5"), ("4", "0.7"))
    name =models.CharField(max_length=200,null=True)
    delay = models.CharField(max_length=2, choices=DELAY,blank=True,null=True)
    def __str__(self):
        return self.name
    
    # def get_absolute_url(self):
    #     return reverse ("jobapp:job_list", kwargs ={'name': self.name})


class Job(models.Model):
    JOB_TYPE = (("1", "Full time"), ("2", "Part time"), ("3", "Internship"))
    employer =models.ForeignKey(Employer, on_delete=models.CASCADE, null=True, blank=True)
    title =models.CharField(max_length=200)
    type = models.CharField(choices=JOB_TYPE, max_length=10)
    description=models.TextField(blank=True,null=True)
    salaryrange=models.CharField(max_length=50,blank=True,null=True)
    salary=models.IntegerField(default=0, blank=True,null=True)
    Location=models.CharField(max_length=2000, blank=True,null=True)
    category =models.ForeignKey(Category,on_delete=models.CASCADE, null=True, blank=True)
    last_date = models.DateTimeField(null=True, blank=True)
    company_name = models.CharField(max_length=100)
    company_description = models.TextField()
    website = models.CharField(max_length=100, default="")
    created_at = models.DateTimeField(default=timezone.now)
    filled = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} posted by {self.employer.name}"
    
    def get_absolute_url(self):
        return reverse ("jobapp:job_details", kwargs ={'pk': self.pk})
    


class Applicant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    firstname = models.CharField(max_length=80, blank=True, null=True)
    lastname = models.CharField(max_length=80, blank=True, null=True)
    email = models.EmailField(unique=True, blank=True, null=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name="applicants")
    created_at = models.DateTimeField(default=timezone.now)
    comment = models.TextField(blank=True, null=True)
    status = models.SmallIntegerField(default=1)
    resume = models.FileField(upload_to='resumes/')
    cover_letter = models.TextField()

    class Meta:
        ordering = ["id"]
        unique_together = ["user", "job"]

    def __str__(self):
        return f"{self.firstname} applied for {self.job.title} job"

    @property
    def get_status(self):
        if self.status == 1:
            return "Pending"
        elif self.status == 2:
            return "Accepted"
        else:
            return "Rejected"



        

jobapp/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from . models import Applicant, Job, Employer


class SignupForm(UserCreationForm):
    username = forms.CharField(max_length=15)
    first_name =forms.CharField(max_length=250)
    last_name =forms.CharField(max_length=250)
    email =forms.CharField(max_length=50)
    
    class Meta:
        model = User
        fields = ['username', 'first_name','last_name','email', 'password1', 'password2']

class CreateJobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ("created_at", "employer",)
        labels = {
            "last_date": "Last Date",
            "company_name": "Company Name",
            "company_description": "Company Description",
        }

    def is_valid(self):
        valid = super(CreateJobForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def clean_last_date(self):
        date = self.cleaned_data["last_date"]
        try:
            if date.date() is None:
                return date
        except:
            if date.date() < datetime.now().date():
                raise ValidationError("Last date can't be before from today")
            return date

    def save(self, commit=True):
        job = super(CreateJobForm, self).save(commit=False)
        if commit:
            job.save()
        return job


class ApplyJobForm(forms.ModelForm):

    class Meta:
        model = Applicant
        fields = ("firstname","lastname","email","resume","cover_letter",)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Employer
        
        fields = "__all__"

jobapp/views.py
from django.shortcuts import render,redirect
from .models import *

from django.views.generic import ListView, DetailView, View
from django.contrib.auth import login,logout,authenticate
from .forms import *
from dataclasses import dataclass

@dataclass
class G:
    employer = Employer.objects
    jobcategory = Category.objects
    job = Job.objects
    applicant = Applicant.objects


# Create your views here.
class HomeView(View):
    template_name = 'home/index.html'
    jb = G.job.all().order_by('-id')[:3]
    categories = G.jobcategory.all()
    
    
    def get(self, request):
        cat = self.categories
        job = self.jb
        return render(request, self.template_name, {"cat": cat, "job":job})

######################### Authentication ##############################

def register(request):
    form = SignupForm()
    if request.method=="POST":
        form= SignupForm(request.POST)
        comp_name = request.POST.get("company_name")
        comp_contact = request.POST.get("company_contact")
        website = request.POST.get("website")
        if form.is_valid():            
            empuser =form.save()
            emp=G.employer.create( username = empuser, company_name = comp_name, 
                     company_contact = comp_contact, website =  website)
            emp.save()
            login(request, empuser)
            return redirect('jobapp:index')
        else:
            return redirect('jobapp:register_employer')
            
    return render(request, 'auth/register_employer.html', {'form': form})


def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username= username, password= password)
        if user is not None:
            login(request, user)
            return redirect('jobapp:index')
        else:
            return redirect('jobapp:login')

    return render(request, "auth/login.html")

def logoutuser(request):
    logout(request)
    return redirect('jobapp:login')      

############################### END OF AUTHENTICATION ##################################


############################### JOB ##################################
class JobDetails(DetailView):
    template_name = "pages/job_details.html"
    model= Job

class JobList(ListView):
    template_name= "pages/job_list.html"
    model = Job


def apply_page(request,id):
    jobdetails = G.job.get(pk=id)
    form=ApplyJobForm( instance= jobdetails )
    if request.method=='POST':
        form=ApplyJobForm(request.POST, request.FILES , instance= jobdetails)
        if form.is_valid():
            form.save()
            new = Applicant(job= G.job.get(pk=id),
                                firstname=form.cleaned_data['firstname'], 
                                lastname=form.cleaned_data['lastname'], 
                    email=form.cleaned_data['email'], resume=form.cleaned_data['resume'],
                    cover_letter=form.cleaned_data['cover_letter'] 
                    )
            new.save()
            
            return redirect('jobapp:index')
    return render(request,'pages/apply.html',{'form':form})

############################### JOB END ##################################

jobapp/templates/home/banner.html
{% load static %}
<!-- Carousel Start -->
<div class="container-fluid p-0">
    <div class="owl-carousel header-carousel position-relative">
        <div class="owl-carousel-item position-relative">
            <img class="img-fluid" src="{% static '' %}img/carousel-1.jpg" alt="">
            <div class="position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center" style="background: rgba(43, 57, 64, .5);">
                <div class="container">
                    <div class="row justify-content-start">
                        <div class="col-10 col-lg-8">
                            <h1 class="display-3 text-white animated slideInDown mb-4">Find The Perfect Job That You Deserved</h1>
                            <p class="fs-5 fw-medium text-white mb-4 pb-2">Vero elitr justo clita lorem. Ipsum dolor at sed stet sit diam no. Kasd rebum ipsum et diam justo clita et kasd rebum sea elitr.</p>
                            <a href="" class="btn btn-primary py-md-3 px-md-5 me-3 animated slideInLeft">Search A Job</a>
                            <a href="" class="btn btn-secondary py-md-3 px-md-5 animated slideInRight">Find A Talent</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Carousel End -->

jobapp/templates/home/filter.html
        <!-- Search Start -->
        <div class="container-fluid bg-primary mb-5 wow fadeIn" data-wow-delay="0.1s" style="padding: 35px;">
            <div class="container">
                <div class="row g-2">
                    <div class="col-md-10">
                        <div class="row g-2">
                            <div class="col-md-4">
                                <input type="text" class="form-control border-0" placeholder="Keyword" />
                            </div>
                            <div class="col-md-4">
                                <select class="form-select border-0">
                                    <option selected>Category</option>
                                    <option value="1">Category 1</option>
                                    <option value="2">Category 2</option>
                                    <option value="3">Category 3</option>
                                </select>
                            </div>
                            <div class="col-md-4">
                                <select class="form-select border-0">
                                    <option selected>Location</option>
                                    <option value="1">Location 1</option>
                                    <option value="2">Location 2</option>
                                    <option value="3">Location 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-dark border-0 w-100">Search</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Search End -->

jobapp/templates/home/home.html
{% comment "" %}

{% extends "main.html" %} {% load static %} 


{%block navbar%}
{% include 'home/navbar.html' %}     
{% endblock %}

{%block banner%}
{% include 'home/banner.html' %}    
{% endblock %}

{%block filter%}
{% include 'home/filter.html' %}      
{% endblock %}

{% block content%}
    <!-- Category Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Explore By Category</h1>
            <div class="row g-4">
                {% if categories %}
                    {% for i in categories %}
                        <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="{{i.get_delay_display}}s">
                            <a class="cat-item rounded p-4" href="{% url 'jobapp:job_list' %}">
                                <i class="fa fa-3x fa-mail-bulk text-primary mb-4"></i>
                                <h6 class="mb-3">{{i.name}}</h6>
                                <p class="mb-0">123 Vacancy</p>
                            </a>
                        </div>

                    {% endfor %}
                {% endif %}
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                    <a class="cat-item rounded p-4" href="">
                        <i class="fa fa-3x fa-tasks text-primary mb-4"></i>
                        <h6 class="mb-3">Project Management</h6>
                        <p class="mb-0">123 Vacancy</p>
                    </a>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                    <a class="cat-item rounded p-4" href="">
                        <i class="fa fa-3x fa-chart-line text-primary mb-4"></i>
                        <h6 class="mb-3">Business Development</h6>
                        <p class="mb-0">123 Vacancy</p>
                    </a>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                    <a class="cat-item rounded p-4" href="">
                        <i class="fa fa-3x fa-hands-helping text-primary mb-4"></i>
                        <h6 class="mb-3">Sales & Communication</h6>
                        <p class="mb-0">123 Vacancy</p>
                    </a>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
                    <a class="cat-item rounded p-4" href="">
                        <i class="fa fa-3x fa-book-reader text-primary mb-4"></i>
                        <h6 class="mb-3">Teaching & Education</h6>
                        <p class="mb-0">123 Vacancy</p>
                    </a>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                    <a class="cat-item rounded p-4" href="">
                        <i class="fa fa-3x fa-drafting-compass text-primary mb-4"></i>
                        <h6 class="mb-3">Design & Creative</h6>
                        <p class="mb-0">123 Vacancy</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Category End -->


{% endblock %}

{% endcomment %}

jobapp/templates/home/index.html
{% extends "main.html" %} {% load static %} 


{%block navbar%}
{% include 'home/navbar.html' %}     
{% endblock %}

{%block banner%}
{% include 'home/banner.html' %}    
{% endblock %}

{%block filter%}
{% include 'home/filter.html' %}      
{% endblock %}

{% block content%}

<!-- Category Start -->
<div class="container-xxl py-5">
    <div class="container">
        <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Explore By Category</h1>
        <div class="row g-4">
            {% if cat %}
                {% for item in cat %}
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="{{i.get_delay_display}}s">
                        <a class="cat-item rounded p-4" href="">
                            <i class="fa fa-3x fa-mail-bulk text-primary mb-4"></i>
                            <h6 class="mb-3">{{ item.name }}</h6>
                            <p class="mb-0">{{ count }} Vacancy</p>
                        </a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
<!-- Category End -->

{% include 'pages/about.html' %}

<!-- Jobs Start -->
<div class="container-xxl py-5">
    <div class="container">
        <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Job Listing</h1>
        <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
            <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
                <li class="nav-item">
                    <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active" data-bs-toggle="pill" href="#tab-1">
                        <h6 class="mt-n1 mb-0">Featured</h6>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="d-flex align-items-center text-start mx-3 pb-3" data-bs-toggle="pill" href="#tab-2">
                        <h6 class="mt-n1 mb-0">Full Time</h6>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="d-flex align-items-center text-start mx-3 me-0 pb-3" data-bs-toggle="pill" href="#tab-3">
                        <h6 class="mt-n1 mb-0">Part Time</h6>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div id="tab-1" class="tab-pane fade show p-0 active">
                    {% if job %}
                        {% for i in job %}
                            <div class="job-item p-4 mb-4">
                                <div class="row g-4">
                                    <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                        <img class="flex-shrink-0 img-fluid border rounded" src="{% static '' %}img/com-logo-1.jpg" alt="" style="width: 80px; height: 80px;">
                                        <div class="text-start ps-4">
                                            <h5 class="mb-3">{{ i.title }}</h5>
                                            <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>{{ i.Location }}</span>
                                            <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>{{ i.get_type_display }}</span>
                                            {% if i.salaryrange == Null %}
                                                <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>{{ i.salary }}</span>
                                            {% else %}
                                                <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>{{ i.salaryrange }}</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                        <div class="d-flex mb-3">
                                            <a class="btn btn-light btn-square me-3" href="#"><i class="far fa-heart text-primary"></i></a>
                                            <a class="btn btn-primary" href="{{ i.get_absolute_url }}">Apply Now</a>
                                        </div>
                                        <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: {{ i.last_date }}</small>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <a class="btn btn-primary py-3 px-5" href="{% url 'jobapp:job_list' %}">Browse More Jobs</a>
                </div> 

                <div id="tab-2" class="tab-pane fade show p-0">
                    <div class="job-item p-4 mb-4">
                        <div class="row g-4">
                            <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                <img class="flex-shrink-0 img-fluid border rounded" src="{% static '' %}img/com-logo-1.jpg" alt="" style="width: 80px; height: 80px;">
                                <div class="text-start ps-4">
                                    <h5 class="mb-3">Software Engineer</h5>
                                    <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>
                                    <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>
                                    <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                <div class="d-flex mb-3">
                                    <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                                    <a class="btn btn-primary" href="">Apply Now</a>
                                </div>
                                <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>
                            </div>
                        </div>
                    </div>
                    <a class="btn btn-primary py-3 px-5" href="{% url 'jobapp:job_list' %}">Browse More Jobs</a>
                </div>
                <div id="tab-3" class="tab-pane fade show p-0">
                    <div class="job-item p-4 mb-4">
                        <div class="row g-4">
                            <div class="col-sm-12 col-md-8 d-flex align-items-center">
                                <img class="flex-shrink-0 img-fluid border rounded" src="{% static '' %}img/com-logo-1.jpg" alt="" style="width: 80px; height: 80px;">
                                <div class="text-start ps-4">
                                    <h5 class="mb-3">Software Engineer</h5>
                                    <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>New York, USA</span>
                                    <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>Full Time</span>
                                    <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>$123 - $456</span>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                                <div class="d-flex mb-3">
                                    <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                                    <a class="btn btn-primary" href="">Apply Now</a>
                                </div>
                                <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: 01 Jan, 2045</small>
                            </div>
                        </div>
                    </div>
                    <a class="btn btn-primary py-3 px-5" href="">Browse More Jobs</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Jobs End -->


<!-- Testimonial Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <h1 class="text-center mb-5">Our Clients Say!!!</h1>
        <div class="owl-carousel testimonial-carousel">
            <div class="testimonial-item bg-light rounded p-4">
                <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                <p>Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded" src="{% static '' %}img/testimonial-1.jpg" style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">Client Name</h5>
                        <small>Profession</small>
                    </div>
                </div>
            </div>
            <div class="testimonial-item bg-light rounded p-4">
                <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                <p>Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded" src="img/testimonial-2.jpg" style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">Client Name</h5>
                        <small>Profession</small>
                    </div>
                </div>
            </div>
            <div class="testimonial-item bg-light rounded p-4">
                <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                <p>Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded" src="img/testimonial-3.jpg" style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">Client Name</h5>
                        <small>Profession</small>
                    </div>
                </div>
            </div>
            <div class="testimonial-item bg-light rounded p-4">
                <i class="fa fa-quote-left fa-2x text-primary mb-3"></i>
                <p>Dolor et eos labore, stet justo sed est sed. Diam sed sed dolor stet amet eirmod eos labore diam</p>
                <div class="d-flex align-items-center">
                    <img class="img-fluid flex-shrink-0 rounded" src="img/testimonial-4.jpg" style="width: 50px; height: 50px;">
                    <div class="ps-3">
                        <h5 class="mb-1">Client Name</h5>
                        <small>Profession</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Testimonial End -->
{% endblock %}

jobapp/templates/home/navbar.html
<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
  <a href="{% url 'jobapp:index' %}" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
      <h1 class="m-0 text-primary">JobEntry</h1>
  </a>
  <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
      <div class="navbar-nav ms-auto p-4 p-lg-0">
          <a href="{% url 'jobapp:index' %}" class="nav-item nav-link active">Home</a>
          <a href="#" class="nav-item nav-link">About</a>
          <div class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
              <div class="dropdown-menu rounded-0 m-0">
                  <a href="{% url 'employerprofile:profile' %}" class="dropdown-item">profile</a>
                  <a href="{% url 'jobapp:job_list' %}" class="dropdown-item">job list</a>
                  <a href="#" class="dropdown-item">Job Detail</a>
              </div>
          </div>
          <div class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
              <div class="dropdown-menu rounded-0 m-0">
                  <a href="#" class="dropdown-item">Job Category</a>
                  <a href="#" class="dropdown-item">Testimonial</a>
                  <a href="#" class="dropdown-item">404</a>
              </div>
          </div>
          <a href="#" class="nav-item nav-link">Contact</a>
      </div>
      {% if request.user.is_authenticated %}
      <span ><a  class="user px-3" href ="{% url 'jobapp:logout' %}"> Logout</a></span>
      <span class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Hello, {{request.user}}</a>
      <!-- <span class="user">  &nbsp;</span> -->
      {% else %}
        <span ><a class="user px-3" href="{% url 'jobapp:login' %}">Login</a></span>
        <a href="{% url 'jobapp:register_employer' %}" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Post A Job<i class="fa fa-arrow-right ms-3"></i></a>
      {% endif  %}
  </div>
</nav>
<!-- Navbar End -->