employerprofile/urls.py
from django.urls import path
from .views import *

app_name = 'employerprofile'

urlpatterns = [
    path('profile/',profile,name='profile'),
    path('edit-profile/',proedit,name='proedit'),
    path('create-job/',createjob,name='create_job'),
    path('edit-job/<str:pk>/',editjob,name='create_job'),
    path('listjob/',listjob,name='listjob'),
]

jobapp/urls.py
from django.urls import path
from .views import *

app_name = 'jobapp'

urlpatterns = [
    path('',HomeView.as_view(),name='index'),
    path('register/',register,name='register_employer'),
    path('signin/',signin,name='login'),
    path('logout/',logoutuser,name='logout'),
    path('list/',JobList.as_view(),name='job_list'),
    path('details/<pk>/',JobDetails.as_view(),name='job_details'),
    path('apply/<str:id>/',apply_page,name='apply'),
]

jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls')),
    path('',include('employerprofile.urls'))
]





if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employerprofile/models.py
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import User

# Create your models here.   

class Employer(models.Model):
    gender=(
        ('Male','male'),
        ('Female','female'),
        ('Other','other'),
    )
    username =models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name=models.CharField(max_length=200,blank=True, null=True)
    dob=models.DateField(blank=True, null=True)
    gender= models.CharField(max_length=200, blank=True, null=True, choices=gender)
    company_contact= models.CharField(max_length=200, blank=True, null=True)
    email= models.EmailField(unique=True)
    company_name =models.CharField(max_length=200,blank=True, null=True)
    company_address=models.TextField(blank=True, null=True)
    website=models.URLField(blank=True, null=True)

    def __str__(self):
        return self.username.username

jobapp/models.py
from django.utils import timezone

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from employerprofile.models import Employer

# Create your models here.


class Category(models.Model):
    DELAY = (("1", "0.1"), ("2", "0.3"), ("3", "0.5"), ("4", "0.7"))
    name =models.CharField(max_length=200,null=True)
    delay = models.CharField(max_length=2, choices=DELAY,blank=True,null=True)
    def __str__(self):
        return self.name
    
    # def get_absolute_url(self):
    #     return reverse ("jobapp:job_list", kwargs ={'name': self.name})


class Job(models.Model):
    JOB_TYPE = (("1", "Full time"), ("2", "Part time"), ("3", "Internship"))
    employer =models.ForeignKey(Employer, on_delete=models.CASCADE, null=True, blank=True)
    title =models.CharField(max_length=200)
    type = models.CharField(choices=JOB_TYPE, max_length=10)
    description=models.TextField(blank=True,null=True)
    salaryrange=models.CharField(max_length=50,blank=True,null=True)
    salary=models.IntegerField(default=0, blank=True,null=True)
    Location=models.CharField(max_length=2000, blank=True,null=True)
    category =models.ForeignKey(Category,on_delete=models.CASCADE, null=True, blank=True)
    last_date = models.DateTimeField(null=True, blank=True)
    company_name = models.CharField(max_length=100)
    company_description = models.TextField()
    website = models.CharField(max_length=100, default="")
    created_at = models.DateTimeField(default=timezone.now)
    filled = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} posted by {self.employer.name}"
    
    def get_absolute_url(self):
        return reverse ("jobapp:job_details", kwargs ={'pk': self.pk})
    


class Applicant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    firstname = models.CharField(max_length=80, blank=True, null=True)
    lastname = models.CharField(max_length=80, blank=True, null=True)
    email = models.EmailField(unique=True, blank=True, null=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name="applicants")
    created_at = models.DateTimeField(default=timezone.now)
    comment = models.TextField(blank=True, null=True)
    status = models.SmallIntegerField(default=1)
    resume = models.FileField(upload_to='resumes/')
    cover_letter = models.TextField()

    class Meta:
        ordering = ["id"]
        unique_together = ["user", "job"]

    def __str__(self):
        return f"{self.firstname} applied for {self.job.title} job"

    @property
    def get_status(self):
        if self.status == 1:
            return "Pending"
        elif self.status == 2:
            return "Accepted"
        else:
            return "Rejected"



        

jobapp/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from . models import Applicant, Job, Employer


class SignupForm(UserCreationForm):
    username = forms.CharField(max_length=15)
    first_name =forms.CharField(max_length=250)
    last_name =forms.CharField(max_length=250)
    email =forms.CharField(max_length=50)
    
    class Meta:
        model = User
        fields = ['username', 'first_name','last_name','email', 'password1', 'password2']

class CreateJobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ("created_at", "employer",)
        labels = {
            "last_date": "Last Date",
            "company_name": "Company Name",
            "company_description": "Company Description",
        }

    def is_valid(self):
        valid = super(CreateJobForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def clean_last_date(self):
        date = self.cleaned_data["last_date"]
        try:
            if date.date() is None:
                return date
        except:
            if date.date() < datetime.now().date():
                raise ValidationError("Last date can't be before from today")
            return date

    def save(self, commit=True):
        job = super(CreateJobForm, self).save(commit=False)
        if commit:
            job.save()
        return job


class ApplyJobForm(forms.ModelForm):

    class Meta:
        model = Applicant
        fields = ("firstname","lastname","email","resume","cover_letter",)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Employer
        
        fields = "__all__"

jobapp/views.py
from django.shortcuts import render,redirect
from .models import *

from django.views.generic import ListView, DetailView, View
from django.contrib.auth import login,logout,authenticate
from .forms import *
from dataclasses import dataclass

@dataclass
class G:
    employer = Employer.objects
    jobcategory = Category.objects
    job = Job.objects
    applicant = Applicant.objects


# Create your views here.
class HomeView(View):
    template_name = 'home/index.html'
    jb = G.job.all().order_by('-id')[:3]
    categories = G.jobcategory.all()
    
    
    def get(self, request):
        cat = self.categories
        job = self.jb
        return render(request, self.template_name, {"cat": cat, "job":job})

######################### Authentication ##############################

def register(request):
    form = SignupForm()
    if request.method=="POST":
        form= SignupForm(request.POST)
        comp_name = request.POST.get("company_name")
        comp_contact = request.POST.get("company_contact")
        website = request.POST.get("website")
        if form.is_valid():            
            empuser =form.save()
            emp=G.employer.create( username = empuser, company_name = comp_name, 
                     company_contact = comp_contact, website =  website)
            emp.save()
            login(request, empuser)
            return redirect('jobapp:index')
        else:
            return redirect('jobapp:register_employer')
            
    return render(request, 'auth/register_employer.html', {'form': form})


def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username= username, password= password)
        if user is not None:
            login(request, user)
            return redirect('jobapp:index')
        else:
            return redirect('jobapp:login')

    return render(request, "auth/login.html")

def logoutuser(request):
    logout(request)
    return redirect('jobapp:login')      

############################### END OF AUTHENTICATION ##################################


############################### JOB ##################################
class JobDetails(DetailView):
    template_name = "pages/job_details.html"
    model= Job

class JobList(ListView):
    template_name= "pages/job_list.html"
    model = Job


def apply_page(request,id):
    jobdetails = G.job.get(pk=id)
    form=ApplyJobForm( instance= jobdetails )
    if request.method=='POST':
        form=ApplyJobForm(request.POST, request.FILES , instance= jobdetails)
        if form.is_valid():
            form.save()
            new = Applicant(job= G.job.get(pk=id),
                                firstname=form.cleaned_data['firstname'], 
                                lastname=form.cleaned_data['lastname'], 
                    email=form.cleaned_data['email'], resume=form.cleaned_data['resume'],
                    cover_letter=form.cleaned_data['cover_letter'] 
                    )
            new.save()
            
            return redirect('jobapp:index')
    return render(request,'pages/apply.html',{'form':form})

############################### JOB END ##################################

jobapp/templates/pages/about.html
        <!-- About Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                        <div class="row g-0 about-bg rounded overflow-hidden">
                            <div class="col-6 text-start">
                                <img class="img-fluid w-100" src="img/about-1.jpg">
                            </div>
                            <div class="col-6 text-start">
                                <img class="img-fluid" src="img/about-2.jpg" style="width: 85%; margin-top: 15%;">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid" src="img/about-3.jpg" style="width: 85%;">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid w-100" src="img/about-4.jpg">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                        <h1 class="mb-4">We Help To Get The Best Job And Find A Talent</h1>
                        <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Tempor erat elitr rebum at clita</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Aliqu diam amet diam et eos</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Clita duo justo magna dolore erat amet</p>
                        <a class="btn btn-primary py-3 px-5 mt-3" href="">Read More</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- About End -->

jobapp/templates/pages/apply.html
{% extends "main.html" %}

{% load static %}


<!-- title section -->

{%block navbar%}
{% include 'home/navbar.html' %}     
{% endblock %}

<!--content -->
{% block content %}
<div class="col-12 bg-light">
    <br><br><br>
    <form action="{% url 'jobapp:apply' jobdetails.pk  %}" method="POST" class="sign w-75 mx-auto" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-success mi mb-4">Submit</button>
    </form>
</div>

{% endblock content %}

jobapp/templates/pages/job_details.html
{% extends "main.html" %} {% load static %} 


{%block navbar%}
{% include 'home/navbar.html' %}     
{% endblock %}

{% block content%}
<!-- Jobs Start -->
<div class="container-xxl py-5">
    <div class="container">
        <p class="mb-4"><a href="{% url 'employerprofile:create_job' object.pk %}">edit</a></p>
        <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
            <h1 class="mb-4">{{ object.title }}</h1>
            <p><i class="fa fa-check text-primary me-3"></i>{{ object.Location }}</p>
            <p class="mb-4"> {{ object.type }} </p>
            <p><i class="fa fa-check text-primary me-3"></i>{{ object.description }}</p>
            {% if object.salaryrange == Null %}
                <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>{{ object.salary }}</span>
            {% else %}
                <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>{{ object.salaryrange }}</span>
            {% endif %}
            <p><i class="fa fa-check text-primary me-3"></i>{{ object.company_name }}</p>
            <a class="btn btn-primary py-3 px-5 mt-3" href="{% url 'jobapp:apply' object.pk %}">Apply</a>
        </div>
    </div>
</div>
<!-- Jobs End -->
{% endblock %}

jobapp/templates/pages/proedit.html
{% extends "main.html" %}

{% load static %}


<!-- title section -->

{%block navbar%}
{% include 'home/navbar.html' %}     
{% endblock %}

<!--content -->
{% block content %}
<div class="col-12 bg-light">
    <br><br><br>
    <a class="nav-link mb-3 profdit" href="{% url 'employerprofile:profile' %}"> <-- Profile</a>
    <form action="{% url 'employerprofile:proedit' %}" method="POST" class="sign w-75 mx-auto" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-success mi mb-4">Submit</button>
    </form>
</div>

{% endblock content %}

jobapp/templates/pages/profile.html
{% extends "main.html" %}

{% load static %}


<!-- title section -->


{%block navbar%}
{% include 'home/navbar.html' %}     
{% endblock %}

<!--content -->
{% block content %}
<div class="container-flui">
    <div class="row justify-content-start">
        <div class="col-12 col-md-3">
            <nav class="navbar navbar-expand-sm navbar-light bg-transparent nav-edit">
                <a class="navbar-toggler border-0" type="button" data-toggle="collapse" href="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                    <!-- <span class="navbar-toggler-icon"></span> -->
                    <span class="navbar-toggler-icon rounded log" style="font-size: 1rem;"></span>
                    <!-- <span><strong>SideBar</strong></span> -->
                </a>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0" style="display: inline-block;">
                        <a class="nav-link mb-3 link-edit" href="#"><i class="fas fa-files"></i>Dashboard <i class="fas fa-files text-primary"></i></a>
                        <a class="nav-link mb-3 profdit" href="{% url 'employerprofile:proedit' %}">Update</a>
                        <a class="nav-link mb-3 link-edit" href="{% url 'employerprofile:create_job' %}">Post Job</a>
                        <a class="nav-link mb-3 link-edit" href="{% url 'employerprofile:listjob' %}">Job Posted</a>
                        <a class="nav-link profditt mb-3 active" href="#item-1"> Profile </a>
                        <a class="nav-link mb-3 profdit" href="#">Change Password</a>
                        <a class="nav-link mb-3 link-edit" href="#">Appointment</a>
                        <a class="nav-link mb-3 link-edit" href="#">Prescription</a>
                        <a class="nav-link text-muted link-editt" href="#"><small>Help And Support</small></a>
                        <a class="nav-link text-muted link-edite" href="#">Preferences</a>
                    </ul>
                </div>
            </nav>  
        </div>
        <div class="col-12 col-md-9 profile-col">
            <div data-spy="scroll" data-target="#navbar-example3" data-offset="0">
                <p id="item-1">
                    <div class="patient-edit">
                        <div class="container-flui">
                            <div class="row">
                                <!-- <div class="col-md-3 align-self-right">
                                    <img src="" class="image-fluid pt-5 mt-5" alt="click to upload your image here" height="100" width="100">
                                </div> -->
                                <div class="col-12 bg-light">
                                    <h4 class="pient anak pt-5">Client Profile</h4>
                                    <hr>
                                    <br><br>
                                    <div class="row justify-content-between mb-5 pb-5 mr-1">
                                        <div class="img-form col-md-4">
                                            <img src="{{profile.image.url}}" class="rounded-image mt-1" alt="click to upload your image here" height="250" width="370">
                                            <br><br><br><br>
                                            <form action="#" class="pt-4 bg-white small-prof">
                                                <h5 class="ml-3 anak">ABOUT PATIENT</h5>

                                                <div class="form-group ml-3 pt-4">
                                                    <label for="inputName"><h6><strong>Full Name</strong></h6></label>
                                                    <p>{{profile.name|title}}</p>
                                                </div>
                                                
                                                <div class="form-group ml-3">
                                                    <label for="inputName"><h6><strong>Date of Birth</strong></h6></label>
                                                    <p>{{profile.dob}}</p>
                                                </div>
                                                <div class="form-group ml-3">
                                                    <label for="inputEmail"><h6><strong>Email ID</strong></h6></label>
                                                    <p>{{profile.email}}</p>
                                                </div>
                                                <div class="form-group ml-3">
                                                    <label for="inputNumber"><h6><strong>gender</strong></h6></label>
                                                    <p>{{profile.get_gender_display}}</p>
                                                </div>
                                                <hr>
                                                <div class="form-group ml-3">
                                                    <label for="inputAddress"><h6><strong>company_name</strong></h6></label>
                                                    <p>{{profile.company_name}}</p>
                                                </div>
                                            </form>
                                        </div>
                                        &nbsp;
                                        <!-- used bootsrap's scrollspy here -->
                                        <div class="bio-general col-12 col-md-7 bg-white">
                                            <nav id="navbar-example2" class="navbar navbar-light bg-transparent bio">
                                                <ul class="nav nav-pill">
                                                    <li class="nav-item">
                                                        <a class="nav-link head-stuff" href="#fat"><strong>company address</strong></a>
                                                    </li>
                                                    <li class="nav-item">
                                                        <a class="nav-link head-stuff" href="#mdo"><strong>Timeline</strong></a>
                                                    </li>
                                                </ul>
                                            </nav>
                                            <div data-spy="scroll" data-target="#navbar-example2" data-offset="0">
                                                <p id="fat">
                                                    <div class="history mb-5">
                                                        <p>{{profile.company_address}}</p>
                                                    </div>
                                                    <hr>
                                                    <div class="report">
                                                        <h3 class="anak">General Report</h3>
                                                        <small>Blood Pressure</small>
                                                        <div class="progress" style="height: 6px;">
                                                            <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                                                        </div><br>
                                                        <small>Heart Beat</small>
                                                        <div class="progress" style="height: 6px;">
                                                            <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                                        </div><br>
                                                        <small>Haemoglobin</small>
                                                        <div class="progress" style="height: 6px;">
                                                            <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                                        </div><br>
                                                        <small>Sugar</small>
                                                        <div class="progress" style="height: 6px;">
                                                            <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                                        </div>
                                                    </div>
                                                    <hr>
                                                    <div class="height">
                                                        <h3 class="anak">Normal Details</h3>
                                                        <form action="">
                                                            <br>
                                                            <div class="form-group">
                                                                <label for="inputName">company_contact</label>
                                                                <p>{{profile.company_contact}}</p>
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="inputName">website</label>
                                                                <p>{{profile.website}}</p>
                                                            </div>

                                                        </form>
                                                    </div>
                                                </p>

                                                <p id="mdo" class="mdo">
                                                    <i class="far fa-circle"></i>
                                                    <hr>
                                                    <p>This shows time your presence was received and time you were discharged <br>
                                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur 
                                                        accusantium ipsa sapiente necessitatibus dolores veritatis saepe quas? 
                                                        Facilis, dolore facere!
                                                    </p>
                                                </p>
                                               
                                            </div>                            
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}